name: Python Tests with MySQL

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mathquiz_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -utestuser -ptestpass"
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: mathquiz_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysql -h 127.0.0.1 -P 3306 -utestuser -ptestpass -e "SELECT 1" mathquiz_test; then
            echo "MySQL is ready"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Initialize Database Schema
      run: |
        mysql -h 127.0.0.1 -P 3306 -uroot -proot mathquiz_test < schema.sql

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
        if-no-files-found: warn





